### ISSUE TITLE
can your function create digest form of logic function??

### ISSUE THREAD

**Issue by stackprogramer** [fsgdez/Matlab-Karnaugh-Map-Generator-and-Solver#1]
hi, your work is great, i had a question about your code can your code minimize output function
thanks 
best regards stackprogramer

**Comment by fadi-george** [comment]
Hey stack, it tries to get the biggest grouping for each cell. Any extra minimization step is not performed on the resulting string.

There might have been issues for 5 variables+ KMaps which I will need to revisit and update the code, tests, and documentation. Thank you for your interest.

**Comment by fadi-george** [comment]
I know it's been a while but since I just recently went back to recoding it, the new _upcoming_ solution should optimize the logic for up to 4x4 if not greater.

**Comment by fadi-george** [comment]
All methods should work as intended now. If you do find any more issues, please let me know.
Thanks.
