### ISSUE TITLE
Does not fully Reduce

### ISSUE THREAD

**Issue by dsmalenb** [fsgdez/Matlab-Karnaugh-Map-Generator-and-Solver#2]
fsgdez,

Great effort on this script and functions! I wanted to verify that your routines could minimize non-trivial Kmaps. I tested it on full Gray Coded matrices like the one below. Unfortunately, it was unable to reduce it completely although it should since we are supplying all permutations. Take a look and tell me what you think.

I used the Grey Code routine which can be found at: [https://www.mathworks.com/matlabcentral/fileexchange/62403-gray-code-for-all-base-numbers?s_cid=ME_prod_FX](url)

```
clear all;
clc;

A = grayCodes(2,5);
K1 = karnaughMap( [2 , 3] , A , 5);
genLogic( K1 )
```
The output is: **C'E + CE**, which is just **E**.

This gets a bit crazier if you try a different variable setting such as 

```
clear all;
clc;

A = grayCodes(2,5);
K1 = karnaughMap( [1 , 4] , A , 5);
genLogic( K1 )
```
The output is then: **B'C'E + B'CE + BCE + BC'E**, which is again just **E** but the issue is much more pronounced. 

I am curious about your thoughts on the matter. Keep up the great work for the community!

**Comment by fadi-george** [comment]
Hey, thanks a lot for checking out this project!
This was a side project done quickly to help double check my work for a course involving the use of Karnaugh Maps. So there are definitely some existing kinks in there that need to be fixed.

I've updated the description to state the project is a WIP.
Definitely, I would like to go back and fix these things.
I'll be focusing my time on sprucing this up.

**Comment by dsmalenb** [comment]
No problem at all! Looking forward to seeing the updated routine when you get around to it. 

Blue Skies!

**Comment by fadi-george** [comment]
Changed up how my method operates. Now it will assume the last column to be the output.

In the case grayCodes(2,5), there will be duplicate rows for a 2 var x 2 var matrix.

```
K =

  5×9 cell array

    {'AB\CDE'}    {'000'}    {'001'}    {'011'}    {'010'}    {'110'}    {'111'}    {'101'}    {'100'}
    {'00'    }    {'0'  }    {'1'  }    {'1'  }    {'0'  }    {'0'  }    {'1'  }    {'1'  }    {'0'  }
    {'01'    }    {'0'  }    {'1'  }    {'1'  }    {'0'  }    {'0'  }    {'1'  }    {'1'  }    {'0'  }
    {'11'    }    {'0'  }    {'1'  }    {'1'  }    {'0'  }    {'0'  }    {'1'  }    {'1'  }    {'0'  }
    {'10'    }    {'0'  }    {'1'  }    {'1'  }    {'0'  }    {'0'  }    {'1'  }    {'1'  }    {'0'  }

>> solver(K)

ans =

    '(E)'
```

Above configuration can generate a similar expression.

**Comment by fadi-george** [comment]
Here would be the similar expression:
```
K2 = karnaughMap('m(1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31)', [2 3]);
K2 =

  5×9 cell array

    {'AB\CDE'}    {'000'}    {'001'}    {'011'}    {'010'}    {'110'}    {'111'}    {'101'}    {'100'}
    {'00'    }    {'0'  }    {'1'  }    {'1'  }    {'0'  }    {'0'  }    {'1'  }    {'1'  }    {'0'  }
    {'01'    }    {'0'  }    {'1'  }    {'1'  }    {'0'  }    {'0'  }    {'1'  }    {'1'  }    {'0'  }
    {'11'    }    {'0'  }    {'1'  }    {'1'  }    {'0'  }    {'0'  }    {'1'  }    {'1'  }    {'0'  }
    {'10'    }    {'0'  }    {'1'  }    {'1'  }    {'0'  }    {'0'  }    {'1'  }    {'1'  }    {'0'  }

solver(K2)

ans =

    '(E)'

K2 = karnaughMap('m(1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31)', [1 4])
K2 =

  3×17 cell array

  Columns 1 through 9

    {'A\BCDE'}    {'0000'}    {'0001'}    {'0011'}    {'0010'}    {'0110'}    {'0111'}    {'0101'}    {'0100'}
    {'0'     }    {'0'   }    {'1'   }    {'1'   }    {'0'   }    {'0'   }    {'1'   }    {'1'   }    {'0'   }
    {'1'     }    {'0'   }    {'1'   }    {'1'   }    {'0'   }    {'0'   }    {'1'   }    {'1'   }    {'0'   }

  Columns 10 through 17

    {'1100'}    {'1101'}    {'1111'}    {'1110'}    {'1010'}    {'1011'}    {'1001'}    {'1000'}
    {'0'   }    {'1'   }    {'1'   }    {'0'   }    {'0'   }    {'1'   }    {'1'   }    {'0'   }
    {'0'   }    {'1'   }    {'1'   }    {'0'   }    {'0'   }    {'1'   }    {'1'   }    {'0'   }

solver(K2)

ans =

    '(E)'

```

**Comment by fadi-george** [comment]
Closing this issue. Please let me know if know if you find anything else or want to request an additional feature. Thanks.
